[package]
name    = "newsfeed-server"
version.workspace = true
edition.workspace = true

[[bin]]
name = "newsfeed-server"
path = "src/main.rs"

[dependencies]
newsfeed-constants = { path = "../newsfeed-constants" }
newsfeed-config    = { path = "../newsfeed-config" }
newsfeed-models    = { path = "../newsfeed-models" }
newsfeed-db        = { path = "../newsfeed-db" }
newsfeed-service   = { path = "../newsfeed-service" }

axum           = { workspace = true }
tokio          = { workspace = true }
tower          = { workspace = true }
tower-http     = { workspace = true }
tower_governor = { workspace = true }
serde_json     = { workspace = true }
tracing        = { workspace = true }
tracing-subscriber = { workspace = true }
dotenvy        = { workspace = true }
envy           = { workspace = true }
xxhash-rust    = { workspace = true }
utoipa         = { workspace = true }
sha2           = { workspace = true }
subtle         = { workspace = true }
ipnet.workspace = true

[dev-dependencies]
axum-test      = "21.0.0"
hex            = { workspace = true }
sqlx           = { workspace = true }
testcontainers = "0.15"
tokio          = { workspace = true }
tiberius       = { workspace = true }
tokio-util     = { workspace = true }
bb8            = { workspace = true }
bb8-tiberius   = { workspace = true }

[lints]
workspace = true
